services:
  essence_backend:
    image: essence_backend:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: essence_backend
    ports:
      - "8090:8090/tcp"
    networks:
      - essence_network


networks:
  essence_network:
    driver: bridge
